In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

loaded_model = tf.keras.models.load_model('trained_model.keras')

In [2]:
test_dir = rf"C:\Users\{os.getlogin()}\Documents\gitProjects\qualityInspection\in"
test_datagen = ImageDataGenerator(rescale=1./255)
test_data = test_datagen.flow_from_directory(test_dir,
                                              target_size=(200, 200),
                                              batch_size=32,
                                              class_mode='categorical',
                                              shuffle=False)
image_paths = [os.path.join(test_dir, fname) for fname in test_data.filenames]
result = loaded_model.predict(test_data)
class_predictions = (result > 0.5).astype("int32")
for e in zip(class_predictions, test_data.filenames):
    print(e)

Found 8 images belonging to 1 classes.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step
(array([1, 0]), 'samples\\cast_def_0_9966.jpeg')
(array([1, 0]), 'samples\\cast_def_0_997.jpeg')
(array([1, 0]), 'samples\\cast_def_0_999.jpeg')
(array([1, 0]), 'samples\\cast_def_0_9992.jpeg')
(array([0, 1]), 'samples\\cast_ok_0_9971.jpeg')
(array([0, 1]), 'samples\\cast_ok_0_9973.jpeg')
(array([0, 1]), 'samples\\cast_ok_0_9978.jpeg')
(array([0, 1]), 'samples\\cast_ok_0_998.jpeg')


c:\Users\oliver.koehn\Documents\gitProjects\qualityInspection\venvQualInsp311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()
